/*
 * CANopen static indication definitions for slave1 - generated by CANopen DeviceDesigner 2.4.5
 * Do Jul 7 11:14:49 2016
 */

/* protect against multiple inclusion of the file */
#ifndef GEN_INDICATION
#define GEN_INDICATION 1

/* 
   There are not any static indication functions defined.
   If there were some, they would be declared here. 
 */

#endif /* GEN_INDICATION*/
